Style/StringLiterals:
  EnforcedStyle: double_quotes
Layout/LineLength:
  Max: 200
Metrics/BlockLength:
  Max: 90
Style/RedundantReturn:
  Enabled: false
Style/RedundantInterpolation:
  Enabled: false